#
# Module manifest for module 'CMHealthCheck'
#
# Generated by: David Stein
#
# Generated on: 03/29/2018
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\CMHealthCheck.psm1'

# Version number of this module.
ModuleVersion = '1.0.5'

# ID used to uniquely identify this module
GUID = 'e61ecfc4-1895-4e5d-a91e-10fb4311b09a'

# Author of this module
Author = 'David Stein'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = '(c) 2017-2018 David Stein. All rights reserved.'

# Description of the functionality provided by this module
Description = 'ConfigMgr healthcheck data collection and reporting functions'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = '3.0'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Get-CMHealthCheck',
    'Export-CMHealthCheck',
    'Export-CMHealthCheckHTML'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# List of all files packaged with this module
FileList = @(
    '.\Assets\cmhealthcheck.xml',
    '.\Assets\messages.xml',
    '.\Assets\default.css',
    '.\Assets\ocean.css',
    '.\Assets\buildnumbers.txt',
    '.\Docs\Export-CMHealthCheck.md',
    '.\Docs\Export-CMHealthCheckHTML.md',
    '.\Docs\Get-CMHealthCheck.md'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('cmhealthcheck','healthcheck','health','sccm','configmgr','systemcenter')
        # A URL to the license for this module.
        LicenseUri = 'https://opensource.org/licenses/MIT'
        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Skatterbrainz/CMHealthCheck'
        # A URL to an icon representing this module.
        IconUri = 'https://user-images.githubusercontent.com/11505001/32978293-2be8336e-cc0d-11e7-9606-0c3412aaa7cc.png'
        # ReleaseNotes of this module
        ReleaseNotes = @'
## Enhancements

 * Added documentation and improvements to embedded Help content
 * Refactored code
 * Bug fixes
 * Icon added
 * Removed requires -RunAsAdministrator for v3.0 compatibility
 * Modified PSM1 to suit loading on v3.0 vs. v5.x
 * Added HTML option for output
 * Updated build numbers reference list
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable
}
